In [1]:
# today    : Numpy
# next sat : pca (principle compound analysis)
# next sat : Pyspark with databricks 
# next sat : docker creation

In [ ]:
- pandas is dataframe analysis

- numpy is math analysis

- matplotlib is plotting
=========================================
EDA has only pandas not much numpy


In [4]:
import numpy as np

In [5]:
np.__version__

'1.26.4'

**Difference between normal computation vs Numpy computation**

In [6]:
l1=[1,2,3,4]
l2=[10,20,30,40]
l1+l2

[1, 2, 3, 4, 10, 20, 30, 40]

In [7]:
l1=[1,2,3,4]
l2=[10,20,30,40]
[i+j for i,j in zip(l1,l2)]

[11, 22, 33, 44]

In [8]:
l1*l2

TypeError: can't multiply sequence by non-int of type 'list'

In [9]:
l1=[1,2,3,4]
l2=[10,20,30,40]
[i*j for i,j in zip(l1,l2)]

[10, 40, 90, 160]

In [10]:
arr1=np.array(l1)
arr1,l1

(array([1, 2, 3, 4]), [1, 2, 3, 4])

In [11]:
arr2=np.array(l2)
arr2,l2

(array([10, 20, 30, 40]), [10, 20, 30, 40])

In [12]:
arr1+arr2

array([11, 22, 33, 44])

In [13]:
arr1*arr2

array([ 10,  40,  90, 160])

In [14]:
arr1-arr2

array([ -9, -18, -27, -36])

In [15]:
arr1/arr2

array([0.1, 0.1, 0.1, 0.1])

**Dimensions(**dim**)**

In [16]:
l1=[1,2,3,4]
arr1=np.array(l1)
arr1,arr1.ndim

(array([1, 2, 3, 4]), 1)

In [17]:
l1=[1,2,3,4]
l2=['A','B','C','D']
np.array([l1,l2])

array([['1', '2', '3', '4'],
       ['A', 'B', 'C', 'D']], dtype='<U11')

In [18]:
arr2.ndim

1

In [19]:
l1=[1,2,3,4]
l2=['A','B','C','D']
l3=[100,200,300,400]
arr2=np.array([l1,l2,l3])
print(arr2)
print(arr2.ndim)

[['1' '2' '3' '4']
 ['A' 'B' 'C' 'D']
 ['100' '200' '300' '400']]
2


In [20]:
arr1=np.array([1,2,3,4])
print(arr1)
print(arr1.ndim)
print(arr1.shape)

[1 2 3 4]
1
(4,)


In [21]:
arr2=np.array([[1,2,3,4],['A','B','C','D']])
print(arr2)
print(arr2.ndim)
print(arr2.shape)

[['1' '2' '3' '4']
 ['A' 'B' 'C' 'D']]
2
(2, 4)


In [22]:
arr3=np.array([[[1,2,3,4],['A','B','C','D']]])
print(arr3)
print(arr3.ndim)
print(arr3.shape)

[[['1' '2' '3' '4']
  ['A' 'B' 'C' 'D']]]
3
(1, 2, 4)


In [23]:
arr4=np.array([[[[1,2,3,4],['A','B','C','D']]]])
print(arr4)
print(arr4.ndim)
print(arr4.shape)

[[[['1' '2' '3' '4']
   ['A' 'B' 'C' 'D']]]]
4
(1, 1, 2, 4)


In [24]:
arr5=np.array([[
                [1,2,3,4],['A','B','C','D'],
                 [1,2,3,4],['A','B','C','D']
                   ]])
print(arr5)
print(arr5.ndim)
print(arr5.shape)

[[['1' '2' '3' '4']
  ['A' 'B' 'C' 'D']
  ['1' '2' '3' '4']
  ['A' 'B' 'C' 'D']]]
3
(1, 4, 4)


In [25]:
import time
start=time.time()
l1=[i for i in range(10000000)]
l2=[i for i in range(10000000)]
sum([i*j for i,j in zip(l1,l2)])
end=time.time()
print(f'total time:{end-start}')

total time:2.720616340637207


**np.arrange**

In [26]:
np.arange(10),[i for i in range(10)]

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.arange(10000000)

array([      0,       1,       2, ..., 9999997, 9999998, 9999999])

In [38]:
np.arange(10000000)
import time
start=time.time()
arr1=np.arange(10000000)
arr2=np.arange(10000000)
np.sum(arr1*arr2)
end=time.time()
print(f'total time:{end-start}')

total time:0.06134223937988281


- np.ones

- np.zeros

- np.random.rand

- np.full

- np.random.randint

In [40]:
np.ones(3)
# shape(1,2) always tuple() (rows,columns)

array([1., 1., 1.])

In [41]:
np.ones(shape=(2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [42]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [43]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [47]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [44]:
np.full((3,2),5)

array([[5, 5],
       [5, 5],
       [5, 5]])

In [49]:
np.full((4,4),6)

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

In [50]:
np.random.randint(1,100,(3,3))

array([[25, 58, 42],
       [95, 83, 47],
       [75, 81, 32]])

In [52]:
np.random.rand(3,3)

array([[0.80868252, 0.44254936, 0.91151264],
       [0.77371899, 0.52096528, 0.48279998],
       [0.2488811 , 0.81757242, 0.91077708]])